container:
    image: fedora:24
packages:
    - gcc
    - python3-virtualenv
    - python3-tox
    - redhat-rpm-config
tests:
    - python3-tox -e py35 -vv
timeout: 5m
artifacts:
    - build/cover/
    - nosetests.html
